# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 07:09
from __future__ import unicode_literals

import blog.customfield
import blog.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160728_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=blog.customfield.PhoneNumberField(default='01045467082', max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
