# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 07:18
from __future__ import unicode_literals

import blog.customfield
import blog.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160728_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=blog.customfield.PhoneNumberField(default='phone_number_please', max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
            preserve_default=False,
        ),
    ]
