# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 06:36
from __future__ import unicode_literals

import blog.customfield
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160728_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=7, validators=[blog.validators.ZipCodeValidator], verbose_name='새우편번호')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='시/도')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='시/군/')),
                ('roadname', models.CharField(blank=True, max_length=10, verbose_name='도로명')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.customfield.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
