# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 03:17
from __future__ import unicode_literals

import blog.customfield
import blog.models
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160806_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Jall',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.customfield.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.random_name_upload_to),
        ),
    ]
