# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pokemon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lnglat', models.CharField(help_text='경도,위도 포맷으로 입력', max_length=50, validators=[pokemon.models.lnglat_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('captured_at_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Pokemon_type', models.CharField(max_length=10)),
                ('captured_at_Place', models.ManyToManyField(to='pokemon.Place')),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Player')),
            ],
        ),
    ]
