# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='captured_at_time',
            new_name='captured_time',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='captured_at_Place',
            new_name='places',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='captured_by',
            new_name='players',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='Pokemon_type',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
