# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20160715_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('places', models.ManyToManyField(to='pokemon.Place')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Player')),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='Pokemon_type',
            new_name='pokemon_type',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='captured_time',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='places',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='players',
        ),
        migrations.AddField(
            model_name='capture',
            name='pokemons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon'),
        ),
    ]
